### ISSUE TITLE
Microsoft Office apps icons are wrong

### ISSUE THREAD

**Issue by jozefizso** [Basedash/dockhunt#14]
Icons for Microsoft Word, Excel and PowerPoint apps are incorrect.

See these docks:

https://www.dockhunt.com/apps/Microsoft%20Word
https://www.dockhunt.com/apps/Microsoft%20Excel
https://www.dockhunt.com/apps/Microsoft%20PowerPoint

Only Microsoft Outlook is using the correct icon: https://www.dockhunt.com/apps/Microsoft%20Outlook

Expected Office icons:
<img width="356" alt="Screen Shot 2023-02-02 at 15 49 25" src="https://user-images.githubusercontent.com/287778/216357032-56628738-2d80-4568-9856-44519944c724.png">

**Comment by MaxMusing** [comment]
Updated, thanks for the heads up!
