### ISSUE TITLE
Icon Missing for Motion (usemotion.com) Desktop App

### ISSUE THREAD

**Issue by abass** [Basedash/dockhunt#16]
This is what the [Motion](https://usemotion.com/desktop-app) dock icon is:
<img width="127" alt="CleanShot 2023-02-02 at 12 19 53@2x" src="https://user-images.githubusercontent.com/5505994/216412378-1123c8e3-45f8-460a-8367-34b206d94235.png">

And this is what it is showing on Dockhunt:
<img width="111" alt="CleanShot 2023-02-02 at 12 20 19@2x" src="https://user-images.githubusercontent.com/5505994/216412847-cd956d39-c8bf-49e1-9de3-a126210036e3.png">

Appreciate it!

**Comment by MaxMusing** [comment]
Ah yikes, knew we'd run into this at some point 😅

We currently uniquely identify apps by their name, looks like there are two apps with the exact name `Motion`. Will have to do some more significant restructuring of apps + URL schemes to support this.

**Comment by jeremysarchet** [comment]
Woah, thanks for bringing this to our attention @abass. Ok, right. Two different apps going by the same name.

**Comment by jeremysarchet** [comment]
@abass, I've switched your dock to use /your/ Motion. Check it out: https://www.dockhunt.com/users/alexhbass

**Comment by abass** [comment]
Ayyyy, well done, that was quick! Thanks so much!!

**Comment by abass** [comment]
Hey team, so I re-ran Dockhunt because I wanted it to update the logo for Dispatch and it didn't do that + it updated the Motion logo to the wrong one again 😅
![image](https://user-images.githubusercontent.com/5505994/217625632-6a76133e-ab98-439a-ba17-c841e5b0143c.png)
https://www.dockhunt.com/users/alexhbass

New Dispatch logo:
<img width="66" alt="CleanShot 2023-02-08 at 12 53 52@2x" src="https://user-images.githubusercontent.com/5505994/217625600-d9a9b6dd-d5f3-48fb-ae5e-633c861de08e.png">
