### ISSUE TITLE
Error when scanning dock

### ISSUE THREAD

**Issue by xuerzong** [Basedash/dockhunt#17]
When I open the app or run the script `npx dockhunt`, it will throw an error:

```
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

TypeError: Cannot read properties of undefined (reading 'dict')
    at getAppNamesToIconPaths (/snapshot/dist/index.cjs)
    at getDockContents (/snapshot/dist/index.cjs)
```

Test env

MacBook Pro (Retina, 15-inch, Mid 2015)
MacOS Mojave 10.14.6

**Comment by jeremysarchet** [comment]
Hey @xuerzong, thank you for opening this issue. We have a separate repository for the CLI tool. Would you mind if we closed it here, and you re-opened it in the CLI repo? https://github.com/Basedash/dockhunt-cli

Thank you. I'm out of time for the rest of this week, but I'll be able to work on this issue next week.

**Comment by astoilkov** [comment]
I get the same error when running the app. Should I log this into the CLI as well?

![CleanShot 2023-02-04 at 10 30 46@2x](https://user-images.githubusercontent.com/884810/216757447-5d5fe5a4-aa34-4e9b-85da-fd7aeac607ff.png)

**Comment by xuerzong** [comment]
Okay! You can see here https://github.com/Basedash/dockhunt-cli/issues/16
