### ISSUE TITLE
Nota icon is blank

### ISSUE THREAD

**Issue by astoilkov** [Basedash/dockhunt#18]
**Describe the bug**
[Nota](https://nota.md) icon is blank — https://dockhunt.com/apps/Nota

**To Reproduce**
Go to https://dockhunt.com/apps/Nota.

**Expected behavior**
Not be blank.

**Comment by jeremysarchet** [comment]
Hi @astoilkov. Thanks for reaching out about this. Could you provide a link to Nota's website? What I'll do is get their icon and set it manually in our database. Sometimes our CLI tool which scans your dock isn't able to find the icon file for whatever reason, and the app gets added to our database with no image.

**Comment by jeremysarchet** [comment]
Hi @astoilkov. Thanks for reaching out about this. What I'll do is get their icon and set it manually in our database. Sometimes our CLI tool which scans your dock isn't able to find the icon file for whatever reason, and the app gets added to our database with no image.

**Comment by jeremysarchet** [comment]
Ok, looks like their app is invite-only at the moment, so my idea to download it to get at the icon myself isn't easy. Would you be up for digging into the app bundle and attaching the `.icns` file and attaching it here?
Instructions here: https://github.com/Basedash/dockhunt-cli#incorrect-app-icons

**Comment by jeremysarchet** [comment]
I've also reached out to them on Twitter asking them to provide their Icon.
https://twitter.com/JeremySarchet/status/1621564312664907780?s=20&t=2FnYDvkg_1wTiN3pYiZheQ

**Comment by jeremysarchet** [comment]
In the meantime, I was able to get a square icon from their Twitter page. It's not as nice looking there on Dockhunt as I think their official app will be, but it's an improvement.
https://www.dockhunt.com/apps/Nota

**Comment by jeremysarchet** [comment]
Heard back from them via Twitter with their icon. Got it added to our database. Looking good now. Thanks again for opening this issue.

**Comment by astoilkov** [comment]
Awesome thanks for the quick and thorough response.
