### ISSUE TITLE
UnhandledPromiseRejection error from CLI

### ISSUE THREAD

**Issue by jdsimcoe** [Basedash/dockhunt#2]
When I run `npx dockhunt` from iTerm I get the following error:

```
Scanning your dock...

Found the following pinned apps in your dock:

•  Google Chrome
•  Messages
•  Texts
•  Reflect
•  Figma
•  Cron
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Bad response from Dockhunt `check-apps` endpoint".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

Here is my `npx` version details:

```
> npx -v
9.4.0
```

Also I should note that I got this same error when using the downloaded macOS app and I've now moved to the `npx` version which is throwing the same error.

I'm also getting an error when trying to Sign In with my Twitter account `@jdsimcoe`:

https://www.dockhunt.com/api/auth/signin?error=Callback
<img width="668" alt="image" src="https://user-images.githubusercontent.com/275617/215850543-6373fa61-e576-4969-b5b0-5bab2f3a5205.png">

**Comment by jdsimcoe** [comment]
I re-ran the command and now everything works as expected: https://www.dockhunt.com/users/jdsimcoe

**Comment by robertcoopercode** [comment]
Ok great! We were having issues with our DB earlier so that may be why the API call failed.

**Comment by jdsimcoe** [comment]
@robertcoopercode awesome, thanks the update!

**Comment by jeremysarchet** [comment]
> note that I got this same error when using the downloaded macOS app and I've now moved to the `npx` version which is throwing t

Thanks for reaching out about this @jdsimcoe. My best guess is that what you saw was downstream of some database issues we were troubled with earlier today. The timeline matches up. Our CLI tool (`npx dockhunt` and the downloadable macOS app) doesn't respond too gracefully when it receives a bad response from our server.
