### ISSUE TITLE
Incorrect app icon for iMovie

### ISSUE THREAD

**Issue by infinitepower18** [Basedash/dockhunt#21]
App name: iMovie
Link to app on Dockhunt: https://www.dockhunt.com/apps/iMovie

I've included the correct `.icns` file below, found in my Applications directory by right-clicking the app, selecting "Show Package Contents", and navigating to Contents > Resources.

https://drive.google.com/file/d/1nJulQfs26_z58wxFlMocAyxREl-ml2_j/view?usp=sharing

**Comment by MaxMusing** [comment]
Updated, thanks for providing the correct icon!
