### ISSUE TITLE
Doesn't recognize spacers

### ISSUE THREAD

**Issue by Twipped** [Basedash/dockhunt#24]
**Describe the bug**

The dock has the ability to insert empty spaces to create program groups. Dockhunt doesn't recognize these spacers, so instead of looking like this:

![image](https://user-images.githubusercontent.com/231157/217339319-40e5459f-29be-40be-ac57-76e636dd0612.png)

It looks like this:

![image](https://user-images.githubusercontent.com/231157/217339410-51929440-8102-492f-bdfc-24ed301af54e.png)

https://www.dockhunt.com/users/TwippedTech

**To Reproduce**

These two commands insert spacers into the dock configuration:
```sh
defaults write com.apple.dock persistent-apps -array-add '{"tile-type"="spacer-tile";}'
Markup
defaults write com.apple.dock persistent-apps -array-add '{"tile-type"="small-spacer-tile";}'
```

They can then be dragged around just like application icons.

**Comment by MaxMusing** [comment]
Should be fixed (at least when uploading via `npx dockhunt`) by https://github.com/Basedash/dockhunt-cli/pull/9.
