### ISSUE TITLE
Unable to create an user account

### ISSUE THREAD

**Issue by adamatti** [Basedash/dockhunt#29]
**Describe the bug**

I tried to create the account multiple times on webpage and cli, the callback from twitter isn't working

**To Reproduce**

- go to https://www.dockhunt.com/
- press login
- twitter page will open, authorize
- then it will redirect to https://www.dockhunt.com/api/auth/signin?error=OAuthCallback with this blank page:

![image](https://github.com/Basedash/dockhunt/assets/89515/17407d49-7ee1-4a3d-97dc-f68526953e78)

... and if I press anywhere I circle back to authorization / this error page

**Expected behavior**

I should be able to create my user account 😄 

Thanks in advance

**Comment by lxjv** [comment]
i'm also experiencing this

**Comment by GinoGits** [comment]
Yep, same here. It seems like all the blank profiles are in on this.
Any juicy updates on what's going on?

**Comment by luiscarlospando** [comment]
I just noticed this today trying to re-submit my updated dock.
Twitter auth is broken. 🫠

**Comment by adamatti** [comment]
Yea, I am also facing issues to add twitter account on [Beeper](https://www.beeper.com/).
Additional info: I do have 2fa enabled on twitter with security key (physical).

**Comment by MaxMusing** [comment]
Just made an update, can you try again? Twitter API changes broke this 🥲

**Comment by GinoGits** [comment]
I’m able to login, but my profile is still out of sync. For example i don't have a profile picture and my bio isn’t updated here.

After the Cli command:

When going to the link, the page gets stuck at generating dock…

**Comment by MaxMusing** [comment]
We don't have a mechanism to automatically update profile info at the moment, you can create a separate issue for that (or PR if you're up for it!). For now, I manually updated your profile.

Sounds like there's a separate issue with generating your dock, can you put up another separate issue?
