### ISSUE TITLE
Incorrect app icon for Zed

### ISSUE THREAD

**Issue by mxstbr** [Basedash/dockhunt#31]
App name: Zed (https://zed.dev) 
Link to app on Dockhunt: https://www.dockhunt.com/apps/Zed

They recently updated their logo.

I've included the correct `.icns` file below, found in my Applications directory by right-clicking the app, selecting "Show Package Contents", and navigating to Contents > Resources.

[Zed.icns.zip](https://github.com/Basedash/dockhunt/files/14269745/Zed.icns.zip)

**Comment by MaxMusing** [comment]
Thanks for the heads up, updated! Nice dock by the way :)

https://www.dockhunt.com/apps/Zed
