### ISSUE TITLE
Twitter bio is not complete

### ISSUE THREAD

**Issue by birobirobiro** [Basedash/dockhunt#4]
Dockhunt profile: https://www.dockhunt.com/users/birobirobirodev

![image](https://user-images.githubusercontent.com/22185823/215869782-03a0bd9d-af66-491e-be28-362f5cda53b8.png)

Twitter profile: https://twitter.com/birobirobirodev

![image](https://user-images.githubusercontent.com/22185823/215869880-35700410-df95-4715-a003-3273e15f21b1.png)

**Comment by robertcoopercode** [comment]
Fixed this for you!
